{% set name = "dask-mpi" %}
{% set version = "2026.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 10ebe4e4a1d53c12546a08b4275bc762a4676a175cc40b5ecc6ca2c91e8a2e7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dask-mpi = dask_mpi.cli:main

requirements:
  build:
    - hatchling
    - hatch-vcs
  host:
    - python {{ python_min }}
    - pip
    - pyyaml
    - six
  run:
    - python >={{ python_min }}
    - distributed >=2.2.0
    - mpi4py

test:
  requires:
    - mpich
    - pip
    - python {{ python_min }}
  imports:
    - dask_mpi
  commands:
    - pip check
    - dask-mpi --help

about:
  home: https://github.com/dask/dask-mpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Deploy Dask using MPI4Py
  description: |
    Easily deploy Dask in an MPI environment,
    such as one created with the mpirun or mpiexec MPI launch commands.
  doc_url: http://dask-mpi.readthedocs.io
  dev_url: https://github.com/dask/dask-mpi

extra:
  recipe-maintainers:
    - kmpaul
    - andersy005
    - mrocklin
    - jacobtomlinson
