{% set name = "dask-mpi" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 774cd2d69e5f7154e1fa133c22498062edd31507ffa2ea19f4ab4d8975c27bc3

build:
  skip: true  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - dask-mpi = dask_mpi.cli:go

requirements:
  host:
    - python >=3.5
    - pip
    - pyyaml
    - six
  run:
    - python >=3.5
    - distributed >=2.2.0
    - mpi4py

test:
  requires:
    - mpich
  imports:
    - dask_mpi
  commands:
    - dask-mpi --help

about:
  home: https://github.com/dask/dask-mpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Deploy Dask using MPI4Py'
  description: |
    Easily deploy Dask in an MPI environment,
    such as one created with the mpirun or mpiexec MPI launch commands.
  doc_url: http://dask-mpi.readthedocs.io
  dev_url: https://github.com/dask/dask-mpi

extra:
  recipe-maintainers:
    - kmpaul
    - andersy005
    - mrocklin
