{% set name = "dask-mpi" %}
{% set version = "2022.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a04f1d7d35a06cdff506593330d4414ea242c9172498ce191f5742eac499e17

build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dask-mpi = dask_mpi.cli:main

requirements:
  host:
    - python
    - pip
    - pyyaml
    - six
  run:
    - python
    - distributed >=2022.4.0
    - mpi4py

test:
  requires:
    - mpich
    - pip
  imports:
    - dask_mpi
  commands:
    - pip check
    - dask-mpi --help

about:
  home: https://github.com/dask/dask-mpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Deploy Dask using MPI4Py
  description: |
    Easily deploy Dask in an MPI environment,
    such as one created with the mpirun or mpiexec MPI launch commands.
  doc_url: http://dask-mpi.readthedocs.io
  dev_url: https://github.com/dask/dask-mpi

extra:
  recipe-maintainers:
    - kmpaul
    - andersy005
    - mrocklin
    - jacobtomlinson
