appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XX7ZMDq3A8b4TBez6PImfmrFg7q3t83gHGbdzcRTYcyHb9QZGgCDjOLrxAwnTE8MKvj9yLF2w7D6o9ubWPFp9KBrgc6/U4nHZgwN+ysx+39p4zdE5fBIgm+2dt+W+IQ3fwqMrcK7lGR7gPapwETS1uh+np9yKqkBmt54yz0MmzsWswlRqzosVCFEudLRlADdzQoHSBwUKnrHiyScvL951WmRLDSISEKckk2LySD8D0kd89oshT9H9LJ3w+Grrk0IBa8lefZsoht4TtcdIUhLYhqcoLz+jju7d/tYVgENsPpXt+hXuhyUAgIy8bJCPMT07X0qhGtyfLvnEKR/pwxhkgSodb1JgYwTqURJuZlVfwlj7nkYFvY8ujJMLzbe0brDhr/WEvi3NCD69WVIGl/evrgHi5T6wDfWoFBCYhiHhS+8Gr2exDzufjq3N4FDp+s6MlmKchlWNB+OxEIcXLgWJnhEbt2wEsyOxYczkasAd1cQujJcAUxpiNLldfLW3LNbySFzfFjXUwRDguCLH5gJFHg9ZCWZYwaPaEyKaSYGPRaaY05lMYmbb0zHWpXm+Ch68plF5dTnKRUtO5D8vosNV9G+KTrnIpZZ8IznZcduFwibe026ydNSeWopv1SR1Gq2E0Q+mc+UJS0/2Ti0JwZWzg8Hyex/tuanAfnvErYkEDk=}
conda_forge_output_validation: true
